### ISSUE TITLE
USB DAC's not available due to missing libs

### ISSUE THREAD

**Issue by bluesway** [elgeeko1/roon-server-docker#2]
I did all steps mentioned in the readme for USB DAC section but still failed to get it works, until I run following commands
apt-get update
apt-get install alsa-utils
apt-get install --reinstall libasound2 libasound2-data libasound2-plugins

**Comment by elgeeko1** [comment]
After inserting the USB DAC, you may need to restart the docker container or the server itself. I believe this is a known issue listed in the README, discovery does not seem to work if a device is inserted while the container is running. It does seem to work after a restart.

**Comment by elgeeko1** [comment]
Oh I'm sorry I misread your comment. If I understand correctly, you needed to install `alsa-utils libasound2 libasound2-data libasound2-plugins` into your host OS. I'll add this to the readme. Thanks!
