### ISSUE TITLE
Additional ports needed

### ISSUE THREAD

**Issue by begna112** [elgeeko1/roon-server-docker#5]
I just wanted to report that I needed to add additional ports to work. I'm using a bridged network, but don't think that should have influenced it. Before adding these, I was able to detect the server but not connect to it.    
```
ports:
      - "9003:9003/udp"
      - "9100-9200:9100-9200/tcp"
      - "9001-9002:9001-9002/tcp"
      - "9330-9339:9330-9339/tcp"
      - "30000-30010:30000-30010/tcp"
      - "49863:49863/tcp"
      - "52667:52667/tcp"
      - "52709:52709/tcp"
      - "63098-63100:63098-63100/tcp"
```

Got the additional ones from: https://community.roonlabs.com/t/what-are-the-new-ports-that-roon-server-needs-open-in-the-firewall/186023

**Comment by elgeeko1** [comment]
Awesome @begna112 thanks for posting this. I'll check this out in the next few days.

**Comment by elgeeko1** [comment]
Done! Thanks. @begna112 question with bridged networking mode are you able to discover remote devices from your Roon Server?

**Comment by begna112** [comment]
I haven't tested it, honestly. My primary need was windows clients. I could try setting up a pi with one of the network streamers to test. I will try and get back to you.

**Comment by elgeeko1** [comment]
Thanks, really helpful to have a test on this. I'll give it a shot on my network as well. Most of my streamers are pis. I believe Docker bridge mode isn't capable of multicast which appears to be necessary to discover RAAT devices.

**Comment by begna112** [comment]
Well, I'm able to find a volumio device on my network with the Bridge plugin (https://github.com/crieke/volumio-plugins-sources), but the last update of roon completely trashed my server somehow. I can't seem to play anything at all, even from Windows, and it's having trouble seeing my audio devices. 

Not sure if Bridge is RAAT or not. 

Honestly, my experience with Roon hasn't been great so far, so I'm not sure how much more effort I'm going to put into it.
